const fs = require('fs');
const path = require('path');

const newQuestions = `
    { question: "Hvaða ár var Kópavogur stofnaður sem bær?", options: ["1955", "1940", "1965", "1970"], correctIndex: 0 },
    { question: "Hvað heitir dýpsti fjörður á Íslandi?", options: ["Eyjafjörður", "Ísafjarðardjúp", "Borgarfjörður", "Seyðisfjörður"], correctIndex: 0 },
    { question: "Hvaða breska hljómsveit söng 'Yellow Submarine'?", options: ["The Rolling Stones", "The Beatles", "Queen", "Pink Floyd"], correctIndex: 1 },
    { question: "Hver er stærsta plánetan í sólkerfinu okkar?", options: ["Mars", "Satúrnus", "Júpíter", "Úranus"], correctIndex: 2 },
    { question: "Hvað heitir höfuðborg Ástralíu?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correctIndex: 2 },
    { question: "Hvaða málmur er fljótandi við stofuhita?", options: ["Kvikasilfur", "Blý", "Kopar", "Gull"], correctIndex: 0 },
    { question: "Hvaða ár hófst fyrri heimsstyrjöldin?", options: ["1912", "1914", "1918", "1939"], correctIndex: 1 },
    { question: "Hver málaði Monu Lisu?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1 },
    { question: "Hvað eru margir leikmenn inn á vellinum í einu liði í handbolta?", options: ["5", "6", "7", "8"], correctIndex: 2 },
    { question: "Hvaða ávaxtategund er Granny Smith?", options: ["Appelsína", "Epli", "Pera", "Kirsuber"], correctIndex: 1 },
    { question: "Hvaða fugl er stærstur í heimi?", options: ["Kondór", "Strútur", "Páfagaukur", "Örn"], correctIndex: 1 },
    { question: "Hvaða land á landamæri að flestum öðrum löndum?", options: ["Kína", "Rússland", "Bandaríkin", "Brasilía"], correctIndex: 0 },
    { question: "Hvaða ár varð Ísland fullvalda ríki?", options: ["1918", "1944", "1904", "1874"], correctIndex: 0 },
    { question: "Hvað heitir næst stærsta borg Spánar?", options: ["Madrid", "Valencia", "Barcelona", "Sevilla"], correctIndex: 2 },
    { question: "Hvaða stjörnumerki er tímabilið 21. mars til 19. apríl?", options: ["Nautið", "Hrúturinn", "Fiskarnir", "Tvíburarnir"], correctIndex: 1 },
    { question: "Hver skrifaði Harry Potter bækurnar?", options: ["J.R.R. Tolkien", "C.S. Lewis", "J.K. Rowling", "Stephen King"], correctIndex: 2 },
    { question: "Hvaða líffæri framleiðir insúlín?", options: ["Lifrin", "Brisið", "Nýrun", "Maginn"], correctIndex: 1 },
    { question: "Hvaða tungumál er mest talað í Brasilíu?", options: ["Spænska", "Portúgalska", "Franska", "Enska"], correctIndex: 1 },
    { question: "Hvað heitir hæsta fjall Afríku?", options: ["Mont Blanc", "Kilimanjaro", "Mount Everest", "K2"], correctIndex: 1 },
    { question: "Hvaða íslenska sveitarfélag hefur póstnúmerið 200?", options: ["Hafnarfjörður", "Garðabær", "Kópavogur", "Mosfellsbær"], correctIndex: 2 },
    { question: "Hvaða efnatákn stendur fyrir Gull?", options: ["Ag", "Au", "Go", "Gd"], correctIndex: 1 },
    { question: "Hvað er lengsta fljót í heimi?", options: ["Amasonfljót", "Níl", "Mississippifljót", "Jangtse"], correctIndex: 1 },
    { question: "Hver fann upp upptalningu ljósaperunnar (kom henni í almenna notkun)?", options: ["Nikola Tesla", "Thomas Edison", "Albert Einstein", "Alexander Graham Bell"], correctIndex: 1 },
    { question: "Hvað heitir stærsta haf heimsins?", options: ["Atlantshafið", "Indlandshafið", "Kyrrahafið", "Norður-Íshafið"], correctIndex: 2 },
    { question: "Hvaða tveir litir mynda grænan þegar þeim er blandað saman?", options: ["Rauður og gulur", "Blár og gulur", "Rauður og blár", "Svartur og hvítur"], correctIndex: 1 },
    { question: "Hvaða ár kom út fyrsta Star Wars kvikmyndin?", options: ["1977", "1980", "1983", "1975"], correctIndex: 0 },
    { question: "Hver samdi tónlistina við kvikmyndina Jaws (Ókindin)?", options: ["Hans Zimmer", "John Williams", "Ennio Morricone", "Danny Elfman"], correctIndex: 1 },
    { question: "Hvaða dýr hefur svört og hvít röndótt mynstur og býr í Afríku?", options: ["Hlébarði", "Gíraffi", "Sebrahestur", "Tígrisdýr"], correctIndex: 2 },
    { question: "Hvað heitir forseti Frakklands (árið 2024)?", options: ["Francois Hollande", "Nicolas Sarkozy", "Emmanuel Macron", "Jacques Chirac"], correctIndex: 2 },
    { question: "Hvaða á er næst lengst á Íslandi?", options: ["Þjórsá", "Jökulsá á Fjöllum", "Ölfusá", "Hvítá"], correctIndex: 1 },
    { question: "Hvaða heimsálfa er stærst að flatarmáli?", options: ["Afríka", "Norður-Ameríka", "Asía", "Evrópa"], correctIndex: 2 },
    { question: "Í hvaða landi er borgin Kyoto?", options: ["Kína", "Suður-Kórea", "Tæland", "Japan"], correctIndex: 3 },
    { question: "Hvaða mánuður hefur 28 daga (eða 29 í hlaupári)?", options: ["Janúar", "Febrúar", "Mars", "Allir mánuðirnir"], correctIndex: 3 },
    { question: "Hver skrifaði söguna um Múmíndálana?", options: ["Astrid Lindgren", "Tove Jansson", "Hans Christian Andersen", "Roald Dahl"], correctIndex: 1 },
    { question: "Hvað heitir stærsta eyjan í heimi (sem er ekki heimsálfa)?", options: ["Grænland", "Nýja-Gínea", "Borneó", "Madagaskar"], correctIndex: 0 },
    { question: "Hvaða ár fóru Íslendingar fyrst á HM í fótbolta karla?", options: ["2014", "2016", "2018", "2020"], correctIndex: 2 },
    { question: "Hvað heitir stærsta vatnið á Ítalíu?", options: ["Comovatn", "Gardavatn", "Maggiorevatn", "Trasimenovatn"], correctIndex: 1 },
    { question: "Hvaða blóðflokkur er algengastur í heiminum?", options: ["A", "B", "AB", "O"], correctIndex: 3 },
    { question: "Hver leikstýrði kvikmyndinni Titanic?", options: ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Martin Scorsese"], correctIndex: 1 },
    { question: "Hvað heita fylkistákn Bandaríkjanna (stjörnurnar) á fánanum mörg?", options: ["48", "49", "50", "51"], correctIndex: 2 },
    { question: "Hvaða norræna land er ekki í Evrópusambandinu?", options: ["Svíþjóð", "Finnland", "Danmörk", "Noregur"], correctIndex: 3 },
    { question: "Hvaða tegund skýja er oft kallað 'þrumuský'?", options: ["Cirrus", "Stratus", "Cumulonimbus", "Altocumulus"], correctIndex: 2 },
    { question: "Hver er hraðskreiðasta landdýr í heimi?", options: ["Strútur", "Gepard", "Lón", "Antilópa"], correctIndex: 1 },
    { question: "Hvað eru mörg spil í hefðbundnum spilastokki (án jókera)?", options: ["50", "52", "54", "56"], correctIndex: 1 },
    { question: "Hver af eftirfarandi er ekki norræn guð?", options: ["Óðinn", "Þór", "Ares", "Freyr"], correctIndex: 2 },
    { question: "Hvaða hljóðfæri spilaði Louis Armstrong aðallega á?", options: ["Saxófón", "Trompet", "Píanó", "Klarínett"], correctIndex: 1 },
    { question: "Hvaða land framleiðir mest kaffi í heiminum?", options: ["Kólumbía", "Víetnam", "Eþíópía", "Brasilía"], correctIndex: 3 },
    { question: "Hvaða ártal kom COVID-19 fyrst upp sem alþjóðlegur faraldur?", options: ["2018", "2019", "2020", "2021"], correctIndex: 2 },
    { question: "Hvaða tölvuleikur er mest seldi leikur allra tíma?", options: ["Tetris", "Grand Theft Auto V", "Minecraft", "Wii Sports"], correctIndex: 2 },
    { question: "Hvaða heimspekingur sagði 'Ég hugsa, þess vegna er ég'?", options: ["Sókrates", "Immanuel Kant", "René Descartes", "Platon"], correctIndex: 2 },
    { question: "Hvaða lið hefur unnið flesta Meistaradeildartitla karla í fótbolta?", options: ["Barcelona", "Bayern München", "AC Milan", "Real Madrid"], correctIndex: 3 },
    { question: "Hvaða tegund eldsneytis er notuð í flugvélum (þotueldsneyti)?", options: ["Bensín", "Dísel", "Steinolía (Kerosene)", "Metangas"], correctIndex: 2 },
    { question: "Hvaða ár hófust formlega útsendingar Stöðvar 2?", options: ["1984", "1986", "1988", "1990"], correctIndex: 1 },
    { question: "Hvaða land hefur stærsta fólksfjölda í heimi (frá og með 2023/24)?", options: ["Kína", "Indland", "Bandaríkin", "Indónesía"], correctIndex: 1 },
    { question: "Hver skrifaði söguna um Lísu í Undralandi?", options: ["C.S. Lewis", "J.R.R. Tolkien", "Lewis Carroll", "Roald Dahl"], correctIndex: 2 },
    { question: "Hvaða tækni var þróuð af Tim Berners-Lee árið 1989?", options: ["E-mail", "World Wide Web (Veraldarvefurinn)", "Bluetooth", "Wi-Fi"], correctIndex: 1 },
    { question: "Hvað nefnist fræga klukkan í London?", options: ["London Eye", "Big Ben", "Tower Bridge", "Westminster Chime"], correctIndex: 1 },
    { question: "Hvaða grænmeti er þekkt fyrir að láta fólk gráta við skurð?", options: ["Hvítlaukur", "Laukur", "Gulrót", "Rófa"], correctIndex: 1 },
    { question: "Hvaða dýrategund er 'Dúmbó' úr frægu Disney-myndinni?", options: ["Mús", "Fíll", "Hundur", "Köttur"], correctIndex: 1 },
    { question: "Hver er höfuðborg Japans?", options: ["Beijing", "Seoul", "Tókýó", "Osaka"], correctIndex: 2 },
    { question: "Hvað er átt við með skammstöfuninni 'NASA'?", options: ["National Aeronautics and Space Administration", "National Association of Space Astronauts", "North American Space Agency", "National Aerospace and Science Association"], correctIndex: 0 },
    { question: "Hvaða frumefni er það algengasta í alheiminum?", options: ["Súrefni", "Kolefni", "Vetni", "Helíum"], correctIndex: 2 },
    { question: "Hvaða hluti augans gefur því litinn sinn?", options: ["Sjónan", "Hornhimnan", "Sjáaldrið", "Lithimnan (Iris)"], correctIndex: 3 },
    { question: "Hvaða ár lenti Appollo 11 á tunglinu?", options: ["1965", "1969", "1972", "1975"], correctIndex: 1 },
    { question: "Hvaða bandaríski ríki er stærst að flatarmáli?", options: ["Texas", "Kalifornía", "Alaska", "Montana"], correctIndex: 2 },
    { question: "Hver er aðal matseðillinn hjá pandabjörnum?", options: ["Fiskur", "Hunang", "Bambus", "Skordýr"], correctIndex: 2 },
    { question: "Hvað heitir forritunarmálið sem er uppnefnt eftir höggormi?", options: ["Cobra", "Python", "Viper", "Anaconda"], correctIndex: 1 },
    { question: "Hvaða dýr er teiknað á lógó bílaframleiðandans Ferrari?", options: ["Ljón", "Örn", "Hestur", "Naut"], correctIndex: 2 },
    { question: "Hvaða sögupersóna rannsakar glæpi ásamt Dr. Watson?", options: ["Hercule Poirot", "Sherlock Holmes", "Miss Marple", "Inspector Clouseau"], correctIndex: 1 },
    { question: "Hvað er stærsta eyja Miðjarðarhafsins?", options: ["Kýpur", "Korsíka", "Sikiley", "Sardinía"], correctIndex: 2 },
    { question: "Hvaða fræga stytta stendur í höfninni í New York?", options: ["Frelsisstyttan", "Kristsstyttan", "Eiffelturninn", "Litla Hafmeyjan"], correctIndex: 0 },
    { question: "Hvaða litur kemur upp á umferðarljósum eftir gult?", options: ["Grænn", "Rauður", "Blár", "Fer eftir landi"], correctIndex: 1 },
    { question: "Hvaða stærðfræðilegi fasti byrjar á 3.14159?", options: ["e", "Phi", "Pi", "Tau"], correctIndex: 2 },
    { question: "Hver af þessum er ekki tegund af skýjum?", options: ["Cumulus", "Stratus", "Cirrus", "Aura"], correctIndex: 3 },
    { question: "Hvað kallast fólk sem borðar ekki kjöt né dýraafurðir af neinu tagi?", options: ["Grænmetisætur", "Vegan (Sælkerar)", "Pescetarian", "Flexitarian"], correctIndex: 1 },
    { question: "Hvaða fjallgarður aðskilur Evrópu og Asíu?", Úralfjöll: 0, "Himalaya": 1, "Kákasus": 2, "Alparnir": 3, options: ["Úralfjöll", "Himalaya", "Kákasus", "Alparnir"], correctIndex: 0 },
    { question: "Hvaða land framleiðir bílategundina Volvo?", options: ["Þýskaland", "Svíþjóð", "Ítalía", "Frakkland"], correctIndex: 1 },
    { question: "Hvað nefnist vökvin sem rennur úr trjám og verður síðan að rafi?", options: ["Blóð", "Trjákvoða", "Hunang", "Safi"], correctIndex: 1 },
    { question: "Hvaða bandaríski söngvari gekk undir viðurnefninu 'The King of Rock and Roll'?", options: ["Johnny Cash", "Chuck Berry", "Elvis Presley", "Jerry Lee Lewis"], correctIndex: 2 },
    { question: "Hvaða dýr byggir stíflur úr trjám og greinum í ám?", options: ["Ottur", "Bifur", "Minkur", "Þvottabjörn"], correctIndex: 1 },
    { question: "Hvað er andheitið við 'Virkur'?", options: ["Latur", "Óvirkur", "Dauður", "Kyrr"], correctIndex: 1 },
    { question: "Hvaða drykkur er gerður úr gerjuðum þrúgum?", options: ["Bjór", "Vín", "Vodki", "Romm"], correctIndex: 1 },
    { question: "Hvað heitir minnsta bein mannslíkamans, sem staðsett er í eyranu?", options: ["Ístað", "Hamar", "Steðji", "Sköflungur"], correctIndex: 0 },
    { question: "Hvað stendur 'GPS' fyrir?", options: ["Global Positioning System", "Global Pointing Service", "Geographic Position Sensor", "General Path System"], correctIndex: 0 },
    { question: "Hvaða litur er táknrænn fyrir konungsfjölskyldur og völd víða um heim?", options: ["Grænn", "Fjólublár", "Bleikur", "Gulur"], correctIndex: 1 },
    { question: "Hvað kallaðist fyrsti gervihnötturinn sem sendur var út í geim?", options: ["Apollo", "Voyager", "Sputnik 1", "Hubble"], correctIndex: 2 },
    { question: "Hver af þessum kryddum er búið til úr trjáberki?", options: ["Svartur pipar", "Kanill", "Vanilja", "Múskat"], correctIndex: 1 },
    { question: "Hvaða land hefur borgina Rio de Janeiro?", options: ["Argentína", "Kólumbía", "Perú", "Brasilía"], correctIndex: 3 },
    { question: "Hvaða íslenska hljómsveit var upphaflega nefnd 'Þeyr'?", options: ["Nei, Þeyr var bara Þeyr", "Mezzoforte", "Sykurmolarnir", "Purrkur Pillnikk"], correctIndex: 0 },
    { question: "Hvað kallast fóbían þegar fólk er hrætt við kóngulær?", options: ["Claustrophobia", "Arachnophobia", "Agoraphobia", "Acrophobia"], correctIndex: 1 },
    { question: "Hvaða íslenska söngkona sigraði í raunveruleikaþættinum The Voice í Frakklandi?", options: ["Emilíana Torrini", "Hafdís Huld", "Margrét Rán", "Erna Hrönn (Eða engin slík) - Svarið er engin slík"], correctIndex: 3 }
`;

const fileStr = fs.readFileSync(path.join(__dirname, 'dulur_global/src/lib/games/kviss/content.ts'), 'utf8');

const targetIndex = fileStr.indexOf('export const KVISS_QUESTIONS_EN');
let beforeEnd = fileStr.lastIndexOf('];', targetIndex);

const newFileContent = fileStr.slice(0, beforeEnd) + newQuestions + fileStr.slice(beforeEnd);

fs.writeFileSync(path.join(__dirname, 'dulur_global/src/lib/games/kviss/content.ts'), newFileContent);

console.log("Successfully appended 90 questions!");
