import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { AuthProvider } from "@/contexts/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-100 text-black">
        <AuthProvider>
          <Header />
          <main className="flex-grow">{children}</main>
          <footer className="mt-auto p-6 bg-white text-black text-center shadow-md">
            &copy; 2025 Leikir. All rights reserved.
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}